# Put this in your repos .github/workflows/fmt.yml
name: "Check formatting"
on:
  pull_request:
  push:
    branches:
    - main

permissions: {}

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v30
      with:
        # Revision from nixpkgs-unstable: https://status.nixos.org/
        # Important to not change over time, so that CI won't
        # suddenly start failing once the formatter version is updated!
        nix_path: nixpkgs=https://github.com/NixOS/nixpkgs/archive/2d068ae5c6516b2d04562de50a58c682540de9bf.tar.gz
    - name: Install treefmt and formatters
      run: |
        nix-env -f '<nixpkgs>' -iA treefmt2 nixfmt-rfc-style
        if [[ ! -e treefmt.toml ]]; then
          cat > treefmt.toml <<EOF
        [formatter.nixfmt]
        command = "nixfmt"
        includes = ["*.nix"]
        EOF
        fi
    - name: Run treefmt
      run: treefmt --ci
